//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cintera.DAL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Script {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Script() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cintera.DAL.Script", typeof(Script).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE VIEW Customers  
        ///AS  
        ///select ISNULL(ParentId, -1) as Id, count(*) as Child from region where ParentId &lt;&gt;-1 GROUP BY ParentId .
        /// </summary>
        internal static string AddView1 {
            get {
                return ResourceManager.GetString("AddView1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Table #CountyByState (
        ///Country nvarchar(200) NOT NULL,
        ///State nvarchar(200) NOT NULL,
        ///County nvarchar(200) NOT NULL
        ///)
        ///
        ///insert #CountyByState(Country, State, County) values 
        ///
        ///(&apos;Jordan&apos;, &apos;Irbid&apos;, &apos;Ramtha&apos;),
        ///(&apos;Jordan&apos;, &apos;Irbid&apos;, &apos;Ramtha2&apos;),
        ///(&apos;Jordan&apos;, &apos;Irbid&apos;, &apos;Ramtha3&apos;),
        ///(&apos;Jordan&apos;, &apos;Amman&apos;, &apos;Bayader&apos;),
        ///(&apos;Jordan&apos;, &apos;Amman&apos;, &apos;Bayader2&apos;),
        ///(&apos;Jordan&apos;, &apos;Amman&apos;, &apos;Bayader3&apos;).
        /// </summary>
        internal static string CountryByState {
            get {
                return ResourceManager.GetString("CountryByState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO REGION
        ///SELECT distinct Country as Name,  null as ParentId, &apos;Country&apos; as Discriminator from #CountyByState 
        ///
        ///INSERT INTO REGION
        ///SELECT distinct State as Name, RegionId as ParentId, &apos;State&apos; as Discriminator  from #CountyByState JOIN REGION on Name =  Country and Discriminator=&apos;Country&apos;
        ///
        ///INSERT INTO REGION
        ///SELECT distinct County as Name, RegionId as ParentId, &apos;County&apos; as Discriminator  from #CountyByState JOIN REGION on Name =  State and Discriminator=&apos;State&apos;.
        /// </summary>
        internal static string InsertRegion {
            get {
                return ResourceManager.GetString("InsertRegion", resourceCulture);
            }
        }
    }
}
